### PR TITLE
chore: add components normalize style

### PR DESCRIPTION
**Pull request by AxelPeter**
Add default style for custom tags of our components

### CODE REVIEW

**Comment by AxelPeter** [comment]
Some components have no style on the root tag, since there is no class on it. 
This means we have components with `block` with a container having `display: inline` by default.

I don't see why it's annoying for making grids. Do you have examples ?

**Comment by AxelPeter** [comment]
@rfougier That's why i want to add base style on custom tag element. `display: inline` will not apply your `height: 100%` :)

**Comment by AxelPeter** [comment]
@rfougier This behaviour result from the fact that the custom component is `display: inline`. But it means too that we have block elements in inline ones. 
I'm not a big fan of this case, since it could lead to unexpected results, fixed by DIY without solving the core of the problem.

Maybe we should discuss this with the others and get their feedbacks :)

**Comment by jleveugle** [comment]
Hello @AxelPeter,
Your pull request is now closed due to inactivity.
Feel free to re-open it if you have any update.
Anna Bot for OVH UX <3

**Pull request closed without merging**
