### PR TITLE
build: remove deprecated npm-scripts-* from devDependencies

### PR DESCRIPTION
**Pull request by antleblanc**
# Remove deprecated `npm-scripts-*`

### ⚙️ Build

Theses devDependencies has been replaced with the actual configuration 
that we use across all repositories from the organization.

Pay attention that now the `scope-enum` is no more restricted to the 
components' list.

0b74853 — build: remove deprecated npm-scripts-* from devDependencies

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build#219.0 ✘  
* 
  * build ✘

**Comment by ovh-cds** [comment]
CDS Report yarn-build-ui-kit#1457.0 ✘  
* build
  * build ✘

**Comment by ovh-cds** [comment]
CDS Report build#220.0 ✘  
* 
  * build ✘

**Comment by ovh-cds** [comment]
CDS Report yarn-build-ui-kit#1458.0 ✘  
* build
  * build ✘

**Comment by AxelPeter** [comment]
@antleblanc Can you see me before requesting this kind of change, especially for anything concerning the build of the v3 ? More informations, and why it has been decided like that, is still welcome.

**Comment by antleblanc** [comment]
@AxelPeter If you prefer I can open an Issue but just bear in mind that this Pull Request is
just about dropping `npm-scripts-*`.

## Why?

`npm-scripts-*` has been released and installed across multiple repository in order to provide an auto-generated CHANGELOG task.

Theses packages was not published (nor moved) to the ovh-ux' organization and we do not have any controls. It will be complicated if we have to update it such as adding patches or new features for instance.

## How?

Actually all `npm-scripts-*` dependencies and any related configuration has been replaced by what I suggest for the OVH UI Kit.

In meantime, I have also do theses changes across all `ovh-manager-*` repositories as well.

If you thinks that theses changes should target the v2* instead, then I will update this Pull Request.

Feel free to give me your feedbacks.

Thanks!

**Comment by ovh-cds** [comment]
CDS Report yarn-build#1019.0 ■   
* build &amp; test
  * build ✔ 
  * test ■

**Comment by AxelPeter** [comment]
Done a rebase

**Comment by ovh-cds** [comment]
CDS Report yarn-build-ui-kit#1483.0 ✘  
* build
  * build ✘

**Comment by ovh-cds** [comment]
CDS Report build#245.0 ✘  
* 
  * build ✘

**Pull request merged**
