### PR TITLE
fix(dist): add a compiled css for usage without less

### PR DESCRIPTION
**Pull request by makidelille**
add compiled css for direct usage without having to recompiled the kit when used as dependency

### CODE REVIEW

**Comment by jimmyfortinx** [comment]
@mlarose I don't remember why we dropped that "feature". Is it OK with you if we enable it again ?

**Comment by antleblanc** [comment]
Maybe take a look at a `postinstall` script if it could be helpful.

**Comment by mlarose** [comment]
@jimmyfortinx afaik the feature was never automated. maybe we could look into adding a travis plan to build that css only on master branch - keeping in mind that conflict resolution on dist files such as this is a pita.

i think this pr does not resolve this need. but the concern and need is valid ; open an issue?

**Comment by makidelille** [comment]
thanks, i'll make an issue instead :)

**Pull request closed without merging**
