### PR TITLE
Build/update storybook 5.3

### PR DESCRIPTION
**Pull request by AxelPeter**
- Update dependencies to latest minor version
- Update configuration and stories for Storybook 5.3

### CODE REVIEW

**Comment by antleblanc** [comment]
Since you are bumping mostly `devDependencies`, couldn't be the case for those too?

- eslint (5.16.0) ❯ 6.8.0
- eslint-config-airbnb-base (13.2.0) ❯ 14.0.0
- eslint-loader (2.2.1) ❯ 3.0.3
- file-loader (4.3.0) ❯ 5.0.2
- husky (3.1.0) ❯ 4.0.7
- karma-coverage (1.1.2) ❯ 2.0.1
- karma-jasmine (2.0.1) ❯ 3.1.0
- stylelint (10.1.0) ❯ 13.0.0
- stylelint-config-standard (18.3.0) ❯ 19.0.0

**Comment by FredericEspiau** [comment]
@antleblanc maybe in another PR, this one is already big enough :)

**Comment by AxelPeter** [comment]
@antleblanc Yes, I could. Like said in description, it was only bumped to latest minors for now.
But I'll take a look on these packages to test with the latest majors :)

**Comment by AxelPeter** [comment]
New patch version from Storybook, I've fixup the impacted commit

**Pull request merged**
